# Generated by Django 3.1.6 on 2021-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorFirstName', models.CharField(max_length=50)),
                ('DoctorLastName', models.CharField(max_length=50)),
                ('DoctorUserName', models.CharField(max_length=100)),
                ('DoctorEmail', models.EmailField(max_length=254)),
                ('DoctorPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor_ID', models.IntegerField()),
                ('PatientFirstName', models.CharField(max_length=50)),
                ('PatientLastName', models.CharField(max_length=50)),
                ('PatientUserName', models.CharField(max_length=100)),
                ('PatientEmail', models.EmailField(max_length=254)),
                ('PatientPassword', models.CharField(max_length=100)),
                ('blood_pressure', models.CharField(max_length=20, null=True)),
                ('medications', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
